#pragma once

#define ERR_CHANOPRIVSNEEDED_MESSAGE "You are not a channel operator"
#define ERR_NOTONCHANNEL_MESSAGE "You are not on that channel"
#define ERR_NOSUCHCHANNEL_MESSAGE "No such channel"
#define ERR_NOSUCHNICK_MESSAGE "No such nickname"
#define ERR_NORECIPIENT_MESSAGE "No recipient given"
#define ERR_NOTEXTTOSEND_MESSAGE "No text to send"
#define ERR_NEEDMOREPARAMS_MESSAGE "Need more params"
#define ERR_USERNOTINCHANNEL_MESSAGE "User not in channel"
#define ERR_ALREADYREGISTERED_MESSAGE "Already registered"
#define ERR_NICKNAMEINUSE_MESSAGE "Nickname already in use"
#define ERR_NICKCOLLISION_MESSAGE "Nickname collision"
#define RPL_ENDOFNAMES_MESSAGE "End of /NAMES list"
#define RPL_NOTOPIC_MESSAGE "No topic is set"
#define RPL_ENDOFINVITELIST_MESSAGE "End of /INVITE list"
#define RPL_WELCOME_MESSAGE "Welcome to our IRC server!"
#define RPL_MOTDSTART_MESSAGE "Message of the day"
#define RPL_ENDOFMOTD_MESSAGE "End of /MOTD command"
#define ERR_NOMOTD_MESSAGE "No message of the day"
#define ERR_NOORIGIN_MESSAGE "No origin was given"
#define ERR_ERRONEUSNICKNAME_MESSAGE "Invalid nickname"

enum NumericReplyCode {
	RET_ZERO = 0,
	RPL_WELCOME = 1,
	RPL_YOURHOST = 2,
	RPL_CREATED = 3,
	RPL_MYINFO = 4,
	RPL_ISUPPORT = 5,
	RPL_CHANNELMODEIS = 324,
	RPL_NOTOPIC = 331,
	RPL_TOPIC = 332,
	ERR_NEEDMOREPARAMS = 461,
	ERR_ALREADYREGISTERED = 462,
	ERR_NONICKNAMEGIVEN = 431,
	ERR_KEYSET = 467,
	RPL_WHOREPLY = 352,
	RPL_ENDOFWHO = 315,
	ERR_NOCHANMODES = 477,
	ERR_UNKNOWNMODE = 472,
	ERR_CHANNELISFULL = 471,
	ERR_BADCHANNELKEY = 475,
	ERR_INVITEONLYCHAN = 473,
	ERR_ERRONEUSNICKNAME = 432,
	ERR_NICKNAMEINUSE = 433,
	ERR_NICKCOLLISION = 436,
	RPL_YOUREOPER = 381,
	RPL_NAMREPLY = 353,
	RPL_ENDOFNAMES = 366,
	ERR_NOTONCHANNEL = 442,
	ERR_CHANOPRIVSNEEDED = 482,
	ERR_NOSUCHCHANNEL = 403,
	ERR_NORECIPIENT = 411,
	ERR_NOTEXTTOSEND = 412,
	ERR_NOSUCHNICK = 401,
	ERR_USERNOTINCHANNEL = 441,
	ERR_PASSWDMISMATCH = 464,
	RPL_INVITING = 341,
	RPL_INVITELIST = 336,
	RPL_ENDOFINVITELIST = 337,
	RPL_MOTDSTART = 375,
	RPL_MOTD = 372,
	RPL_ENDOFMOTD = 376,
	ERR_NOSUCHSERVER = 402,
	ERR_NOMOTD = 422,
	ERR_NOORIGIN = 409
};
